#!/usr/bin/env python3
"""
Smart Attendance System - Setup Script
This script helps you set up the application quickly
"""

import os
import secrets
import sys

def print_header():
    """Print welcome header"""
    print("=" * 60)
    print("🎓 SMART ATTENDANCE SYSTEM - SETUP WIZARD")
    print("=" * 60)
    print()

def check_python_version():
    """Check if Python version is compatible"""
    if sys.version_info < (3, 8):
        print("❌ Error: Python 3.8 or higher is required")
        print(f"   Current version: {sys.version}")
        sys.exit(1)
    print(f"✅ Python version: {sys.version.split()[0]}")

def check_dependencies():
    """Check if required packages are installed"""
    print("\n📦 Checking dependencies...")
    
    required_packages = ['flask', 'supabase', 'python-dotenv', 'werkzeug']
    missing_packages = []
    
    for package in required_packages:
        try:
            __import__(package.replace('-', '_'))
            print(f"   ✅ {package}")
        except ImportError:
            print(f"   ❌ {package} - NOT INSTALLED")
            missing_packages.append(package)
    
    if missing_packages:
        print("\n⚠️  Missing packages detected!")
        print("   Run: pip install -r requirements.txt")
        return False
    
    return True

def create_env_file():
    """Create .env file with user input"""
    print("\n🔧 Setting up environment variables...")
    
    if os.path.exists('.env'):
        response = input("   .env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("   Skipping .env creation")
            return
    
    print("\n   Please provide your Supabase credentials:")
    print("   (You can find these in your Supabase project settings)")
    print()
    
    supabase_url = input("   Supabase URL: ").strip()
    supabase_key = input("   Supabase Anon Key: ").strip()
    
    # Generate a secure secret key
    secret_key = secrets.token_hex(32)
    
    env_content = f"""# Smart Attendance System - Environment Variables
# Generated by setup.py

# Supabase Configuration
SUPABASE_URL={supabase_url}
SUPABASE_KEY={supabase_key}

# Flask Secret Key (auto-generated)
SECRET_KEY={secret_key}

# Application Settings
FLASK_ENV=development
FLASK_DEBUG=True
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        print("\n   ✅ .env file created successfully!")
        print(f"   🔑 Secret key generated: {secret_key[:20]}...")
    except Exception as e:
        print(f"\n   ❌ Error creating .env file: {e}")

def create_directories():
    """Create necessary directories if they don't exist"""
    print("\n📁 Creating directory structure...")
    
    directories = [
        'templates',
        'static',
        'static/css',
        'static/js',
        'static/images'
    ]
    
    for directory in directories:
        if not os.path.exists(directory):
            os.makedirs(directory)
            print(f"   ✅ Created: {directory}")
        else:
            print(f"   ℹ️  Exists: {directory}")

def print_database_instructions():
    """Print instructions for database setup"""
    print("\n" + "=" * 60)
    print("📊 DATABASE SETUP INSTRUCTIONS")
    print("=" * 60)
    print("""
1. Go to your Supabase project dashboard
2. Navigate to: SQL Editor → New Query
3. Copy and paste the contents of 'database_setup.sql'
4. Click 'Run' to execute the SQL script
5. Verify that tables were created successfully

The script will create:
   ✓ users table (staff and students)
   ✓ otp table (OTP codes)
   ✓ attendance table (attendance records)
   ✓ Demo users (staff@example.com, student@example.com)
   ✓ Indexes for performance
   ✓ Views for reporting
""")

def print_demo_credentials():
    """Print demo login credentials"""
    print("\n" + "=" * 60)
    print("👤 DEMO CREDENTIALS")
    print("=" * 60)
    print("""
STAFF ACCOUNT:
   Email: staff@example.com
   Password: staff123

STUDENT ACCOUNT:
   Email: student@example.com
   Password: student123
""")

def print_run_instructions():
    """Print instructions to run the application"""
    print("\n" + "=" * 60)
    print("🚀 HOW TO RUN THE APPLICATION")
    print("=" * 60)
    print("""
1. Ensure database is set up (see instructions above)
2. Run the Flask application:
   
   python app.py

3. Open your browser and navigate to:
   
   http://localhost:5000

4. Login with demo credentials (see above)
""")

def verify_files():
    """Verify that all required files exist"""
    print("\n📋 Verifying project files...")
    
    required_files = [
        'app.py',
        'supabase_config.py',
        'requirements.txt',
        'database_setup.sql',
        'README.md',
        'templates/base.html',
        'templates/login.html',
        'templates/staff_dashboard.html',
        'templates/student_dashboard.html',
        'static/css/style.css',
        'static/js/main.js',
        'static/js/staff.js',
        'static/js/student.js'
    ]
    
    missing_files = []
    for file in required_files:
        if os.path.exists(file):
            print(f"   ✅ {file}")
        else:
            print(f"   ❌ {file} - MISSING")
            missing_files.append(file)
    
    if missing_files:
        print("\n   ⚠️  Some files are missing!")
        return False
    
    return True

def main():
    """Main setup function"""
    print_header()
    
    # Check Python version
    check_python_version()
    
    # Verify files
    if not verify_files():
        print("\n❌ Setup incomplete: Some files are missing")
        print("   Please ensure all project files are present")
        sys.exit(1)
    
    # Check dependencies
    deps_ok = check_dependencies()
    
    if not deps_ok:
        response = input("\n   Install dependencies now? (Y/n): ")
        if response.lower() != 'n':
            print("\n   Installing dependencies...")
            os.system('pip install -r requirements.txt')
        else:
            print("\n   Please install dependencies manually before running the app")
    
    # Create directories
    create_directories()
    
    # Create .env file
    response = input("\n   Do you want to configure environment variables now? (Y/n): ")
    if response.lower() != 'n':
        create_env_file()
    else:
        print("\n   ⚠️  Remember to create .env file manually before running the app")
    
    # Print instructions
    print_database_instructions()
    print_demo_credentials()
    print_run_instructions()
    
    print("\n" + "=" * 60)
    print("✅ SETUP COMPLETE!")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Set up your Supabase database (see instructions above)")
    print("2. Run: python app.py")
    print("3. Visit: http://localhost:5000")
    print("\nFor more information, see README.md")
    print("\n" + "=" * 60)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user")
        sys.exit(0)
    except Exception as e:
        print(f"\n\n❌ Setup error: {e}")
        sys.exit(1)
